### ISSUE TITLE
Versão responsiva

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#10]

**Comment by almirfilho** [comment]
Caralho, tá ficando show @yurigoytacaz! Essa vai ser a maior contribuição pro l8p ever!
Algumas coisas que acho legal pensar à respeito:
- aumentar margens laterais do texto (layout phone)
- espaçamento entre posts pode melhorar. acho que dá pra remover completamente essa margem entre os posts, deixando o fundo todo branco (com exceção ao topo e rodapé)

Mais uma vez, tá ficando show!

**Comment by yurigoytacaz** [comment]
@almirfilho, prefere manter a margem entre os posts (article) no desktop? mesmo que a largura da janela seja menor que 700px?

**Comment by yurigoytacaz** [comment]
#298 pull-request feito. (=

**Comment by almirfilho** [comment]
Está contemplado em #307 para versão v2. Fechando.
