### ISSUE TITLE
Adicionar números dos posts

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/loopinfinito.com.br#122]
De forma bem discreta, na página de cada post

**Comment by almirfilho** [comment]
@caiogondim http://d.pr/i/92Ee
isso só na view do post

**Comment by almirfilho** [comment]
@caiogondim fechado!

**Comment by caiogondim** [comment]
Commit man!

**Comment by almirfilho** [comment]
Dei o merge na minha branch de layout, ela só tinha o commit dessa issue mesmo, não tinha começado nada sobre o novo layout ainda.

**Comment by caiogondim** [comment]
Upou?
