### ISSUE TITLE
Adicionar eventos do Google Analytics a links

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/loopinfinito.com.br#124]
- autores de posts (home, tag e post);
- twitter, rss e fork (menu inferior);
- redes dos autores (sobre).

**Comment by almirfilho** [comment]
Trabalhando nisso.
/cc @caiogondim

**Comment by caiogondim** [comment]
Boto fé!

**Comment by almirfilho** [comment]
Event trackers adicionados. Também adicionei na página de projetos.
