### ISSUE TITLE
Fix no cake task

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#129]
Cake task deploy dispara um warning
"path.existsSync is now called `fs.existsSync`."

**Comment by caiogondim** [comment]
Esse bug é da versão atual do CoffeeScript.
Já foi feito o fix, mas ainda não lançaram na versão estável do CoffeeScript.

**Comment by caiogondim** [comment]
Esqueci de novo de fechar a issue pelo commit, mas o commit é o ae47c41dd0c3c53beddb0a2b7e900a2df589f27b

Adicionei cores no output do cake task deploy e modifiquei o servidor de stage.loopinfinito.com.br para staging.loopinfinito.com.br

**Comment by almirfilho** [comment]
Esqueceu também de botar o assigned e os labels =)

**Comment by caiogondim** [comment]
Verdade.
Foi mal =/
