### ISSUE TITLE
PNG Crush nos ícones

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/loopinfinito.com.br#13]
Minimizar o tamanho dos ícones.

**Comment by almirfilho** [comment]
As imagens já foram otimizadas há muito tempo. Fechando essa issue.

**Comment by caiogondim** [comment]
Na verdade vou fazer um Grunt task ou Cake task pra otimizar todas as imagens de forma automática.

**Comment by almirfilho** [comment]
Então pode criar uma issue pra isso. Essa aqui eu lembro que era porque os
ícones estavam muito pesados.

2013/1/15 Caio Gondim notifications@github.com

> Na verdade vou fazer um Grunt task ou Cake task pra otimizar todas as
> imagens de forma automática.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/loopinfinito/loopinfinito.com.br/issues/13#issuecomment-12282703.

## 

Almir Filho

## _almirfilho.com_

LAWS - Laboratory of Advanced Web Systems
_laws.deinf.ufma.br_

**Comment by caiogondim** [comment]
Perfeito.

Só falando que a gente ainda precisa de um jeito automático de otimizar as imagens.

**Comment by almirfilho** [comment]
De acordo.
