### ISSUE TITLE
Post sobre acelerômetro

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#137]

**Comment by caiogondim** [comment]
Vamo se inspirar nesse jogo pra iOS: http://itunes.apple.com/us/app/labyrinth-lite-edition/id284940503?mt=8
E usar alguma lib pra tratar colisão, talvez o Box2D JS http://box2d-js.sourceforge.net/index2.html

**Comment by almirfilho** [comment]
Trabalhando nisso. /cc @caiogondim
