### ISSUE TITLE
Aside do post não acompanha o scroll quando não há referências do post

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/loopinfinito.com.br#138]
Este problema só ocorre na view interna do post.
Exemplo: http://loopinfinito.com.br/2012/09/10/emulando-chefes-de-cozinha/

**Comment by almirfilho** [comment]
Essa é tua então @caiogondim xD

**Comment by caiogondim** [comment]
Vou resolver hoje a noite

**Comment by almirfilho** [comment]
O problema persiste quando não há nem a seção de Referências nem a seção de Comentários dentro do post.

**Comment by caiogondim** [comment]
Não consigo mais reproduzir esse bug. 
Acho que já foi corrigido.

Qualquer coisa, só reabrir.
