### ISSUE TITLE
Conteúdo da página Projetos

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/loopinfinito.com.br#15]

**Comment by almirfilho** [comment]
- Full the Face
- Surfing with the Alien
- Less CSS BR
- Bootstrap BR

**Comment by almirfilho** [comment]
- CoffeeScript BR

**Comment by almirfilho** [comment]
@caiogondim mais alguma idéia?

**Comment by caiogondim** [comment]
Por enquanto tá bom demais =)
