### ISSUE TITLE
Implementar tracker do Google Analytics em todo erro de JS

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#175]
Utilizar o evento window.onerror

**Comment by almirfilho** [comment]
boa!

**Comment by caiogondim** [comment]
@almirfilho , tu pode criar um custom event no Google Analytics pra mim e me falar como posso disparar?
Que eu já implemento isso.

**Comment by almirfilho** [comment]
blz! Resolvemos isso hoje mais tarde..

**Comment by almirfilho** [comment]
Trabalhando nisso.
