### ISSUE TITLE
Resumo de posts com markdown

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/loopinfinito.com.br#177]
Atualmente escrevemos com HTML, vamo colocar pra markdown usando a função `markdownify` do liquid nos templates.

**OBS.: Não esquecer de editar os resumos de todos os posts antigos que estão escritos com HTML.**

**Comment by caiogondim** [comment]
Bom demais!
Assim fica tudo no padrão.

Essa issue é minha =)

**Comment by almirfilho** [comment]
Tô ligado que você gosta é do **easy** ahahha

**Comment by caiogondim** [comment]
Não pode ter nunca task easy, na verdade =/
Muito menos bug.

**Comment by yurigoytacaz** [comment]
EasyTask-Catcher? é isso mesmo, Caio?

**Comment by almirfilho** [comment]
Dormiu no ponto, @caiogondim! =P
