### ISSUE TITLE
Forçar o cliente baixar sempre a versão mais nova de CSS

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/loopinfinito.com.br#178]
Quando fazemos alguma atualização no CSS, o navegador nunca carrega de primeira (sempre temos que recarregar a página). Isso faz com que o usuário tenha uma experiência ruim.

**Comment by caiogondim** [comment]
O chato é que desse jeito o CSS é sempre baixado e nunca vem do cache.
Se tivesse um jeito de mudar esse timestamp só na hora que o CSS mudasse ficaria perfeito. 
O melhor dos dois mundos.

**Comment by almirfilho** [comment]
Ai só com back-end, que dá pra buscar o data de modificação do arquivo =/
