### ISSUE TITLE
CSS Filters

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#19]
Falar sobre essa nova feature que a Adobe implementou no WebKit.
São filtros meio Photoshop agora disponíveis pelo CSS.

Exemplo:
- http://davidwalsh.name/css-filters

**Comment by caiogondim** [comment]
Mais um post sobre CSS filters
http://notes.jayrobinson.org/post/20911710381/check-out-this-post-i-contributed-to-webkitbits

Quem sabe um novo projeto não seria emularmos os efeitos do Instagram, fazendo disso uma lib em LESS e disponibilizando aqui no GitHub?!

Que acha, @almirfilho ?

**Comment by almirfilho** [comment]
Ótima idéia! Você é o cara.

**Comment by caiogondim** [comment]
Eu vou fazer esse post.
No domingo tá online.

Vai ser também o 1º post com highlight de código.
Vou usar muito provavelmente o Rainbow.js

**Comment by caiogondim** [comment]
Post feito!
Fechando issue.

**Comment by caiogondim** [comment]
Atualizar o post com o filtro drop-shadow
http://blog.teamtreehouse.com/css-filter-effects

**Comment by almirfilho** [comment]
E ai? 2 meses já..

**Comment by yurigoytacaz** [comment]
3 months and counting.

**Comment by caiogondim** [comment]
Finalmente no ar!
