### ISSUE TITLE
Post sobre CSS Selectors Level 4

### ISSUE THREAD

**Issue by yurigoytacaz** [loopinfinito/loopinfinito.com.br#194]
http://coding.smashingmagazine.com/2013/01/21/sneak-peek-future-selectors-level-4/

**Comment by almirfilho** [comment]
Não entendi, esse post já existe:
http://loopinfinito.com.br/2012/06/24/novos-seletores-css4/

**Comment by yurigoytacaz** [comment]
Desculpa, Almir.
Eu não lembrava desse post.

Talvez pudesse ser feito uma atualização do post. 
Só isso mesmo. 
Pode deletar essa issue.

**Comment by almirfilho** [comment]
De boa po, de qualquer forma valeu pela idéia =)
