### ISSUE TITLE
Verificar se está na branch master na hora do deploy

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/loopinfinito.com.br#203]

**Comment by caiogondim** [comment]
Quando migrar o deploy pro Grunt começo essa tarefa

**Comment by caiogondim** [comment]
Já que o Grunt já está funcionando, amanhã começo a trabalhar nessa task.

**Comment by caiogondim** [comment]
Dá um testada ai.
Teste aqui e deu certo.
