### ISSUE TITLE
Resolver bug no botão de busca

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/loopinfinito.com.br#210]
**Comportamento esperado:**
Ao clicar no botão de busca quando a mesma já está aberta, deve fechar a área de busca.

**Comportamento atual:**
A área de busca não fecha pelo clique no botão de busca.

**Comment by yurigoytacaz** [comment]
Testei no Chrome e Firefox (latest @ mac) e tá funfando normal. 
Parece que não é sempre que acontece.

**Comment by almirfilho** [comment]
Justamente.. como te expliquei, não conseguimos reproduzir o cenário em que acontece o erro.

**Comment by luanmuniz** [comment]
Eu consegui reproduzir o bug.
No Firefox, ele faz o blur do input, tira a classe depois faz o click da div e coloca novamente.
Mas o clique tem que ser rápido, pois o blur aparentemente só acontece no "clickUp" (tipo o keyUp, quando você tira o dedo da tecla, mas com o clique, sim)
Aqui está uma imagem do que acontece:
![http://s28.postimg.org/yjpvuaaul/loopinfinito.gif](http://s28.postimg.org/yjpvuaaul/loopinfinito.gif)

Dei uma olhada no código, mas não consegui pensar em muitas soluções, podemos colocar um setInterval no blur ou mudar a maneira como é o show do search.
O que vocês acham?

**Comment by caiogondim** [comment]
Show, @luanmuniz 
Vou dar uma olhada melhor com essa sua dica.

**Comment by luanmuniz** [comment]
Como é uma questão de provável refatoração do código, não queria enviar um PR sem antes discutir com vocês uma solução legal, porem, estou disposto a ajudar! :)

**Comment by caiogondim** [comment]
@luanmuniz não esqueci do seu pull request.
Deixa ficar um pouco mais tranquilo que vou resolver esse bug com vc =)

**Comment by almirfilho** [comment]
Dropped due redesign.
