### ISSUE TITLE
Erro de conteúdo no post sobre CSS Filters

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/loopinfinito.com.br#224]
http://loopinfinito.com.br/2012/04/14/css-filters/

Na parte onde fala de brightness, 50% na verdade diminui o brilho pela metade, sendo 100% o brilho original e 200% o dobro do brilho.
É bom dar uma revisada também nos outros filtros que tenham uso semelhante.

**Comment by caiogondim** [comment]
Pode validar de novo?

**Comment by caiogondim** [comment]
CLOSED!
