### ISSUE TITLE
Proteger staging com senha

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#229]

**Comment by yurigoytacaz** [comment]
e quanto ao SOURCE do site inteiro no github?
qual a lógica de esconder o staging quando posso clonar o repositorio
inteiro? (e acessar todos os posts que ainda não foram publicados)

**Comment by almirfilho** [comment]
@yurigoytacaz e quanto a uma coisa chamada **web crawlers**?

**Comment by yurigoytacaz** [comment]
acho não precisa de senha pra proteger "contra" web crawlers.
robots, htaccess, até js tem solucao pra isso, não?

**Comment by almirfilho** [comment]
Nope. Autenticação simples HTTP, vei.

E quanto ao repositório no github, quantas pessoas vão clonar o repositório inteiro pra procurar um post ou outro que ainda não foi publicado (em todas as branches)? 
Acho que pouquíssimas. Acessar uma url é muito mais fácil.

**Comment by almirfilho** [comment]
@caiogondim a proteção está sendo resetada ao fazer deploy. Favor investigar =)

**Comment by almirfilho** [comment]
\o/
