### ISSUE TITLE
Não deixar os gif sempre rodando.

### ISSUE THREAD

**Issue by felquis** [loopinfinito/loopinfinito.com.br#230]
Isso tira totalmente o meu foco acredito que de outras pessoas também. Que tal deixar os gifs com uma div de overlay e quando passar o mouse essa div sai simulando um "play" e deixando ver o gif...

Considerem.

**Comment by caiogondim** [comment]
Eu transformei os vídeos em GIF pra que ficassem disponíveis no RSS.
To pensando em voltar pra vídeo, já que é bem menor o tamanho e a qualidade bem maior.

Passando pra vídeo também posso fazer melhor o controle de play/pause.

Com GIF dá pra fazer esse cheat do overlay, mas não fica tão bom quanto vídeo.

O que acham de passar pra vídeo apenas?
Eu mostro um botão de play em cima do vídeo, e quando o cara clicar eu do play em loop.
No hover, quando em loop, eu mostro o comando de pause.

/cc @almirfilho

**Comment by almirfilho** [comment]
acho uma boa

2013/4/25 Caio Gondim notifications@github.com

> Eu transformei os vídeos em GIF pra que ficassem disponíveis no RSS.
> To pensando em voltar pra vídeo, já que é bem menor o tamanho e a
> qualidade bem maior.
> 
> Passando pra vídeo também posso fazer melhor o controle de play/pause.
> 
> Com GIF dá pra fazer esse cheat do overlay, mas não fica tão bom quanto
> vídeo.
> 
> O que acham de passar pra vídeo apenas?
> Eu mostro um botão de play em cima do vídeo, e quando o cara clicar eu do
> play em loop.
> No hover, quando em loop, eu mostro o comando de pause.
> 
> /cc @almirfilho
> 
> On 25/abr/2013, at 01:13, Ofelquis Gimenes notifications@github.com
> wrote:
> 
> > Isso tira totalmente o meu foco acredito que de outras pessoas também.
> > Que tal deixar os gifs com uma div de overlay e quando passar o mouse essa
> > div sai simulando um "play" e deixando ver o gif...
> > 
> > Considerem.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/loopinfinito/loopinfinito.com.br/issues/230#issuecomment-17039196
> .

## 

Almir Filho

## _almirfilho.com_

LAWS - Laboratory of Advanced Web Systems
_laws.deinf.ufma.br_

**Comment by yurigoytacaz** [comment]
Acho que em video fica melhor, com os controles play/pause como tu sugeriu,
assim a animação não fica num fps ruim.
E "eu do" é teu cu! Desaprendeu a conjugar o verbo, porra?

2013/4/25 Caio Gondim notifications@github.com

**Comment by caiogondim** [comment]
Beleza, então.

Já tô trabalhando nisso.

**Comment by caiogondim** [comment]
Já está no ar: http://loopinfinito.com.br/2013/04/19/vazamento-de-memoria-em-javascript/

Dêem uma testada e falem se ficou bom.

Não fiz com vídeo pq não consegui dar crop e resize por nenhum software e devido aos codecs.

Se forem testar no Chrome, testem no Canary, pq a versão estável tá com um bug nos eventos `mouseenter` e `mouseleave`.
