### ISSUE TITLE
Seta nas laterais para paginação

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#235]

**Comment by caiogondim** [comment]
Boa referência: http://www.polygon.com/2013/10/26/4862474/video-games-and-motion-sickness-dying-light-techland-fps

**Comment by caiogondim** [comment]
O sprite do site Polygon
![ui_sprite v1a28b61](https://f.cloud.github.com/assets/33044/1416961/322413ce-3f71-11e3-9ca3-a338a02a51e5.png)

**Comment by almirfilho** [comment]
Ainda acha isso relevante, @caiogondim?

**Comment by caiogondim** [comment]
Issue muito antiga.
Vamos fechar e reabrir caso sinta necessidade novamente.
