### ISSUE TITLE
Post sobre CSS Regions

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#24]

**Comment by caiogondim** [comment]
Referência: http://html.adobe.com/webstandards/cssregions/

**Comment by caiogondim** [comment]
Um ótimo post do NetTuts sobre CSS Regions http://net.tutsplus.com/tutorials/html-css-techniques/diving-into-css-regions/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+nettuts+%28Nettuts%2B%29

**Comment by almirfilho** [comment]
Polyfill da Adobe
http://adobe-webplatform.github.io/css-regions-polyfill/?utm_source=html5weekly&utm_medium=email
