### ISSUE TITLE
Post sobre Scoped CSS

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#26]
Scoped CSS é um novo método de escrever CSS "misturado" com o HTML, e estas regras só terão efeito do elemento em que ele foi definido para baixo.

Exemplos:
- http://www.webmonkey.com/2012/04/html5-offers-scoped-css-for-precision-styling/?utm_source=html5weekly&utm_medium=email
- http://updates.html5rocks.com/2012/03/A-New-Experimental-Feature-style-scoped

**Comment by almirfilho** [comment]
Post publicado por mim no Tableless: http://tableless.com.br/scoped-css/
