### ISSUE TITLE
Bug no post “1 ano de Loop Infinito”

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#280]
Acabei de entrar no post e vi que os gráficos não estão carregando.

http://loopinfinito.com.br/2013/04/05/1-ano-de-loop/

To recebendo um erro de sintaxe no console.
Temos que dar una analisada melhor no bug.

**Comment by almirfilho** [comment]
Muito estranho... vou dar uma olhada depois.

**Comment by caiogondim** [comment]
Corrigido.
O erro era que o Jekyll (ou alguma “subtarefa” dele) estava pondo <![CDATA[ entre as tags `style` e `script`.
Criei uma grunt task para remover essas tags após o build do Jekyll.
