### ISSUE TITLE
atualizar o README.md

### ISSUE THREAD

**Issue by danielfilho** [loopinfinito/loopinfinito.com.br#290]
fiz todos os passos, mas o quando tento rodar o jekyll, não rola. nem procurei debugar, lazyweb total.

**Comment by yurigoytacaz** [comment]
precisa de 1 galinha preta, 2 pés de coelho, 1kg de farinha, uma boa reza e
o almir ou o caio benzer teu mac. haha

**Comment by almirfilho** [comment]
O @yurigoytacaz tem razão. Lembra que te disse que tem tanta dependência que queremos migrar pro docpad? hahaha

**Comment by yurigoytacaz** [comment]
haha mas não é impossível.
falando sério, até onde lembro, o maior problema era a versão do ruby.
depois disso já tem o gruntfile com todas as deps.
não era?

2014-02-17 10:20 GMT-03:00 Almir Filho notifications@github.com:

**Comment by danielfilho** [comment]
foi por isso que criei a issue. ia escrever uma matéria surpresa mas FUÉN

**Comment by almirfilho** [comment]
Podemos tentar resolver isso hoje mais tarde =)

**Comment by caiogondim** [comment]
=/

Precisa de uma versão específica do Jekyll.
Fala comigo hoje a noite que a gente resolve isso.

Tá bem chato instalar o loop.
Precisamos melhorar isso.

**Comment by yurigoytacaz** [comment]
Jekyll 0.12.1

2014-02-17 13:20 GMT-03:00 Caio Gondim notifications@github.com:

**Comment by caiogondim** [comment]
Precisamos de um gemfile com todas as dependêncisa **Ruby**

**Comment by caiogondim** [comment]
Setando como um bug

**Comment by almirfilho** [comment]
Acho que isso foi resolvido na issue #145. =*
