### ISSUE TITLE
Adicionar meta tags do open graph específicas para artigos (posts)

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/loopinfinito.com.br#305]
Temos apenas as mais gerais. Adicionar as restantes:
https://developers.facebook.com/docs/reference/opengraph/object-type/article

**Comment by yurigoytacaz** [comment]
usa isso pra testar
https://developers.facebook.com/tools/debug/

**Comment by almirfilho** [comment]
Boa!

**Comment by almirfilho** [comment]
Done.
