### ISSUE TITLE
Opção de compartilhamento de posts

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/loopinfinito.com.br#31]
Botão share para as redes sociais.

**Comment by caiogondim** [comment]
Almir, a gente já faz isso com o Disqus.
Acho melhor não por nada e deixar como tá.

Pode fechar a to-do?

**Comment by almirfilho** [comment]
onde faz isso com o disqus?

**Comment by caiogondim** [comment]
No momento do que tu dá um like

**Comment by almirfilho** [comment]
Ou seja, bem escondido.

**Comment by almirfilho** [comment]
é quase um "não compartilhem".

**Comment by caiogondim** [comment]
A idéia é sugerir o share no momento do like.
Mas isso é uma decisão de interface do Disqus.

**Comment by almirfilho** [comment]
Acho que deveríamos tentar fazer algo. Pode ficar legal..
Se não ficar, deixa de mão.

**Comment by caiogondim** [comment]
Ainda acho que o layout novo que tu fez daria mais resultado que focar nisso agora.

**Comment by almirfilho** [comment]
ninguém disse que era pra focar nisso agora.

**Comment by caiogondim** [comment]
Sou contra, mas se tu quiser muito tentar isso, faz.
Acho que quase ninguém usa isso, e aumenta bastante o tempo de carregamento da página.

O que eu acho legal é saber o número de pessoas que compartilharam, mas isso a gente já tem pelo Disqus

**Comment by almirfilho** [comment]
Feature cancelada. Fechando issue.
