### ISSUE TITLE
Post sobre Herança em JavaScript parte I

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#35]

**Comment by almirfilho** [comment]
### Observações
- relê e marca os pontos chave do texto como negrito/italico;
- declaração da classe em Java deve ser **public abstract class** e seus métodos **abstract void**;
- verifica os erros ortográficos no word;

### Erros
- 'Eles todas herdarão';
- 'objetos do tipo definido usando o comando new.';
- 'todas as propriedades que os objetos deste tipo irão ter **SE** invocarmos o comando new.'
- 'rex instaceof Cachorro';
- 'Pois alguma funcionam';

**Comment by caiogondim** [comment]
Post no ar.
