### ISSUE TITLE
Post sobre CoffeeScript

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#39]

**Comment by caiogondim** [comment]
Esse post vai sair junto com a tradução do site coffeescript.org
/cc @almirfilho

**Comment by caiogondim** [comment]
Se quiser, adiciona essa matéria: http://techcrunch.com/2012/09/13/dropbox-rewrote-its-entire-browser-side-codebase-in-one-week/

Dropbox reescrevei o front-end inteiro em Coffee

**Comment by almirfilho** [comment]
Fábio me mostrou ontem no facebook! Achei foda!
link original: https://tech.dropbox.com/?p=361
