### ISSUE TITLE
Minify de HTML e CSS

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/loopinfinito.com.br#5]
Instalar plugin para realizar minify de código no jekyll.

**Comment by caiogondim** [comment]
Isso também pode virar um post.
O que acha?

Tu poderia falar sobre
- Diminuir tamanho total do site, mostrando quanto era e quanto ficou em kb
- Mostrar a diminuição do tempo de carga do site. Aqui a gente pode inclusive usar aquela ferramenta do Mac pra simular uma internet lenta
- Utilizar a CDN do jQuery e mostrar a diferença da carga entre a CDN e no nosso site normal. E dizer também os pq de se usar uma CDN

Mais alguma idéia?
O que acha?

Esse post é teu, blz?
Deadline: domingo 8/4

**Comment by almirfilho** [comment]
Vou falar logo do pngcrush também =)

**Comment by caiogondim** [comment]
Ia ser massa.
Fala de como otimizar a carga de um site, diminuindo o tamanho do site/aplicação que é enviado para o browser.

Talvez falar sobre a redução do número de requests seja massa também, já que quando se da o minify, pode-se também juntar todos os arquivos em um só. 
Como o Bootstrap faz.
