### ISSUE TITLE
Post sobre Herança em JavaScript parte 2

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#52]
Post do Nettuts que pode ser útil: http://net.tutsplus.com/tutorials/javascript-ajax/prototypes-in-javascript-what-you-need-to-know/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+nettuts+%28Nettuts%2B%29

**Comment by almirfilho** [comment]
@caiogondim já passou da hora hein..

**Comment by caiogondim** [comment]
Depois do data uri eu mando esse
