### ISSUE TITLE
Tutorial: Como colaborar com Loop Infinito

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/loopinfinito.com.br#55]
### Um tutorial de como:
- usar o github;
- dar um fork no projeto;
- submeter um pullrequest

Mais alguma idéia @caiogondim?

**Comment by almirfilho** [comment]
@caiogondim o que acha de usarmos também o wiki do github pra isso?

**Comment by caiogondim** [comment]
O legal da wiki é quando tem bastante conteúdo.
No nosso caso, acho que cabe tudo apenas no README.

Descrição do projeto e como ajudar

**Comment by almirfilho** [comment]
Então vou desativar o wiki desse repo.

**Comment by caiogondim** [comment]
Pode desativar

**Comment by caiogondim** [comment]
Abandonado...
