### ISSUE TITLE
Retirar o botão de dislike nos comentários do Disqus

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#71]
@almirfilho O que acha da gente sumir com o botão de dislike no Disqus?
Acho que ficaria mais simples.

Assim como Facebook, Instagram etc.

O botão que to falando tá indicado nessa imagem:
![botão de dislike](http://cl.ly/073m2T3y2x100Y1z3a1u/Screen%20Shot%202012-05-26%20at%2016.29.16.png)

**Comment by almirfilho** [comment]
@caiogondim acho uma boa, aliás, esse botão do jeito que tá, parece que a galera do lado deu dislike =P
