### ISSUE TITLE
Traduzir o git-scm.com

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#76]
Traduzir o site do Git para o português.
Uma idéia para um próximo projeto.

http://git-scm.com/book/en/Getting-Started

**Comment by rands0n** [comment]
Mas já tem uma [versão](http://git-scm.com/book/pt-br/) em português.
Muito tempo depois kkk

Seria interessante fechar está issue. Tava vendo as abertas e pensei que era de pouco tempo atráz. Mas de 2012. kkk
Mas mesmo assim foi uma ótima iniciativa. Não sei por quem mas foi ótimo :)

Abraços

**Comment by caiogondim** [comment]
Obrigado por lembrar, Randson.
Fechando a issue.
