### ISSUE TITLE
Testar novas fontes no blog

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#78]
Gostei bastante da combinação de fontes desse site: http://johanbrook.com/

Ele utiliza a [Lato](http://www.google.com/webfonts/specimen/Lato) para leitura e a [Bitter](http://www.google.com/webfonts/specimen/Bitter) para os títulos

/cc @almirfilho

**Comment by caiogondim** [comment]
Teste com a **Lato** e **Bitter** não ficaram bons.

Acho que vale um teste com a fonte **Proxima Nova** no lugar da **Helvetica Neue**

**Comment by caiogondim** [comment]
Fiz um teste com a **Proxima nova**

Dá uma olhada nos shots 
- [Proxima Nova](http://cl.ly/2P1L3F3F2C3D0R3F0Y3u) 
- [Helvetica Neue](http://cl.ly/1r1H2U131y1E3D1Z2T1R)

**Comment by almirfilho** [comment]
Gostei do resultado, preciso ver na prática =)

**Comment by caiogondim** [comment]
Pode dar um pull
Upei a fonte no  commit c95b762c0bfef71dcafe5b8479ff6b6529ca613e

**Comment by caiogondim** [comment]
Não sei se ficou melhor, mas ficou muito boa também.

**Comment by almirfilho** [comment]
Ainda não achamos uma fonte mais adequada, fechando esta issue por enquanto.
