### ISSUE TITLE
Fazer templates para autores

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/loopinfinito.com.br#82]
templates separados por autor, desta maneira quando houver alguma mudança de qualquer informação de qualquer autor, não será preciso sair editando todos os posts do mesmo.

**Comment by caiogondim** [comment]
Acho melhor não criar isso.
Um simples find + replace no projeto já resolve.
Vamos tentar ao máximo não adicionar complexidade desnecessária ao projeto.

Isso seria legal de ter, mas é melhor sem.
