### ISSUE TITLE
Footer é carregado apenas na home

### ISSUE THREAD

**Issue by caiogondim** [loopinfinito/loopinfinito.com.br#87]
O footer tá sendo carregado apenas na home, e os scripts não tão sendo carregados, como os scripts do behaviors dos botões da esquerda embaixo (twitter, fork me, rss)

/cc @almirfilho

**Comment by almirfilho** [comment]
Obviamente, já que tiraste do template head.

**Comment by caiogondim** [comment]
Essa issue eu resolvo

**Comment by almirfilho** [comment]
Resolvido no commit c93359a74695608ee8cba2b0f66357f8c838e5bb
