### ISSUE TITLE
Inclusão de imagens dos posts automática

### ISSUE THREAD

**Issue by almirfilho** [loopinfinito/loopinfinito.com.br#95]
- remover a necessidade de inserir as imagens principais dos posts manualmente

**Comment by caiogondim** [comment]
No caso do post Pião da Casa própria, ele não tem imagem interna.
Tem um iframe com o próprio pião.
Então por isso é melhor deixar do jeito que tá.

**Comment by almirfilho** [comment]
Reabrindo issue, pois chegamos a um consenso melhor para esta solução =)
